#!/usr/bin/env -S deno run --allow-read --allow-write --allow-env
/**
 * generate-seed.ts — build supabase/seed.sql from data/employees.csv (DESIGN.md §12).
 *
 * - Roster is TAB-delimited; the name column "Last, First" contains a comma,
 *   so we split on the FIRST comma (multi-word surnames stay intact).
 * - "Reporting to" is resolved by exact raw "Last, First" key, with a
 *   "First Last" fallback for the older export format.
 * - role is inferred (§2): ceo = blank reporting-to or title contains "CEO";
 *   manager = referenced as anyone's reporting-to; else ic.
 * - is_super_admin comes from a hardcoded list, NOT the roster.
 * - Output is idempotent: upsert on email, then resolve reporting lines via an
 *   email self-join (unresolved managers -> reporting_to_id stays NULL).
 *
 * Run from the repo root:
 *   deno run --allow-read --allow-write --allow-env scripts/generate-seed.ts
 */

const CSV_PATH = Deno.args[0] ?? "data/employees.csv";
const OUT_PATH = Deno.args[1] ?? "supabase/seed.sql";

// --- config (§1, §12) -------------------------------------------------------
const ALLOWED_DOMAINS = (Deno.env.get("ALLOWED_EMAIL_DOMAINS") ??
  "dateio.eu,tapix.io,fakeio.eu")
  .split(",").map((d) => d.trim().toLowerCase()).filter(Boolean);

// Hardcoded admin allowlist — add emails here as needed.
const SUPER_ADMIN_EMAILS = new Set(
  ["rachel.green@fakeio.eu"].map((e) => e.toLowerCase()),
);

type Row = {
  nameKey: string; // raw "Last, First"
  firstName: string;
  lastName: string;
  division: string;
  jobTitle: string;
  reportingToRaw: string; // raw "Last, First" of manager (may be "")
  email: string;
  workPhone: string;
};

function splitName(nameKey: string): { last: string; first: string } {
  const i = nameKey.indexOf(",");
  if (i === -1) return { last: nameKey.trim(), first: "" };
  return { last: nameKey.slice(0, i).trim(), first: nameKey.slice(i + 1).trim() };
}

// --- parse ------------------------------------------------------------------
const raw = await Deno.readTextFile(CSV_PATH);
const lines = raw.split(/\r?\n/).filter((l) => l.length > 0);
lines.shift(); // drop header row

const rows: Row[] = [];
const skipped: string[] = [];
for (const line of lines) {
  const f = line.split("\t");
  if (f.length < 5) { skipped.push(`malformed: ${line}`); continue; }
  const nameKey = f[0].trim();
  const { last, first } = splitName(nameKey);
  const email = (f[4] ?? "").trim().toLowerCase();
  const domain = email.split("@")[1] ?? "";
  if (!ALLOWED_DOMAINS.includes(domain)) {
    skipped.push(`domain not allowed (${email || line})`);
    continue;
  }
  rows.push({
    nameKey,
    firstName: first,
    lastName: last,
    division: (f[1] ?? "").trim(),
    jobTitle: (f[2] ?? "").trim(),
    reportingToRaw: (f[3] ?? "").trim(),
    email,
    workPhone: (f[5] ?? "").trim(),
  });
}

// --- uniqueness guards (§12: last names not unique -> key on full string) ---
const byKey = new Map<string, Row>();
const byFirstLast = new Map<string, Row>(); // fallback for "First Last" exports
const emailSeen = new Set<string>();
const dupEmails: string[] = [];
const dupKeys: string[] = [];
for (const r of rows) {
  if (byKey.has(r.nameKey)) dupKeys.push(r.nameKey);
  byKey.set(r.nameKey, r);
  byFirstLast.set(`${r.firstName} ${r.lastName}`.toLowerCase(), r);
  if (emailSeen.has(r.email)) dupEmails.push(r.email);
  emailSeen.add(r.email);
}

// --- referenced-as-manager set ----------------------------------------------
const referenced = new Set<string>();
for (const r of rows) if (r.reportingToRaw) referenced.add(r.reportingToRaw);

function inferRole(r: Row): "ceo" | "manager" | "ic" {
  if (r.reportingToRaw === "" || /ceo/i.test(r.jobTitle)) return "ceo";
  if (referenced.has(r.nameKey)) return "manager";
  return "ic";
}

// --- resolve reporting lines ------------------------------------------------
const reportingPairs: Array<{ child: string; manager: string }> = [];
const unresolved: string[] = [];
for (const r of rows) {
  if (!r.reportingToRaw) continue;
  let mgr = byKey.get(r.reportingToRaw);
  if (!mgr && !r.reportingToRaw.includes(",")) {
    mgr = byFirstLast.get(r.reportingToRaw.toLowerCase());
  }
  if (!mgr) { unresolved.push(`${r.nameKey} -> "${r.reportingToRaw}"`); continue; }
  reportingPairs.push({ child: r.email, manager: mgr.email });
}

// --- emit SQL ---------------------------------------------------------------
const q = (s: string) => `'${s.replace(/'/g, "''")}'`;
const qn = (s: string) => (s ? q(s) : "null");
const out: string[] = [];
out.push("-- supabase/seed.sql — GENERATED by scripts/generate-seed.ts. Do not edit by hand.");
out.push(`-- Source: ${CSV_PATH}. Allowed domains: ${ALLOWED_DOMAINS.join(", ")}.`);
out.push("-- Idempotent: upsert on email; reporting line resolved by email join.");
out.push("");
out.push("begin;");
out.push("");
out.push("insert into public.employees");
out.push("  (email, first_name, last_name, division, job_title, role, is_super_admin, work_phone, is_active)");
out.push("values");
out.push(
  rows.map((r) => {
    const role = inferRole(r);
    const sa = SUPER_ADMIN_EMAILS.has(r.email) ? "true" : "false";
    return `  (${q(r.email)}, ${q(r.firstName)}, ${q(r.lastName)}, ${qn(r.division)}, ${qn(r.jobTitle)}, ${q(role)}, ${sa}, ${qn(r.workPhone)}, true)`;
  }).join(",\n"),
);
out.push("on conflict (email) do update set");
out.push("  first_name     = excluded.first_name,");
out.push("  last_name      = excluded.last_name,");
out.push("  division       = excluded.division,");
out.push("  job_title      = excluded.job_title,");
out.push("  role           = excluded.role,");
out.push("  is_super_admin = excluded.is_super_admin,");
out.push("  work_phone     = excluded.work_phone,");
out.push("  is_active      = excluded.is_active;");
out.push("");
if (reportingPairs.length) {
  out.push("-- resolve reporting_to_id by email (unresolved managers omitted -> NULL)");
  out.push("update public.employees e");
  out.push("set reporting_to_id = m.id");
  out.push("from public.employees m");
  out.push("join (values");
  out.push(reportingPairs.map((p) => `  (${q(p.child)}, ${q(p.manager)})`).join(",\n"));
  out.push(") as map(child_email, manager_email) on m.email = map.manager_email");
  out.push("where e.email = map.child_email;");
  out.push("");
}
out.push("commit;");
out.push("");
await Deno.writeTextFile(OUT_PATH, out.join("\n"));

// --- report -----------------------------------------------------------------
const counts = { ceo: 0, manager: 0, ic: 0 };
for (const r of rows) counts[inferRole(r)]++;
console.log(`Wrote ${OUT_PATH}`);
console.log(`Employees: ${rows.length}  (ceo ${counts.ceo}, manager ${counts.manager}, ic ${counts.ic})`);
console.log(`Super admins: ${rows.filter((r) => SUPER_ADMIN_EMAILS.has(r.email)).map((r) => r.email).join(", ") || "none"}`);
console.log(`Reporting links resolved: ${reportingPairs.length}`);
console.log(`Unresolved reporting (left NULL): ${unresolved.length ? unresolved.join("; ") : "none"}`);
if (dupEmails.length) console.log(`WARN duplicate emails: ${dupEmails.join(", ")}`);
if (dupKeys.length) console.log(`WARN duplicate name keys: ${dupKeys.join(", ")}`);
if (skipped.length) console.log(`Skipped rows (${skipped.length}): ${skipped.join("; ")}`);
